services:
  - type: web
    name: task-tracker
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "8036426582:AAEkGwTAkzfPKPUn0pCMFV4jAkZKzy6mH34"
